# Generated by Django 4.1.3 on 2022-11-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0002_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
