# Generated by Django 4.1.3 on 2022-11-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0003_post_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ip",
            field=models.GenericIPAddressField(null=True),
        ),
    ]
